import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/styles/utils";
import { ThemeProvider } from "@/components/providers/theme";
import { ThemeToggle } from "@/components/theme-toggle";

import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => (
  <html lang="en">
    <body
      className={cn(
        "min-h-screen bg-background font-inter antialiased",
        inter.variable,
      )}
    >
      <ThemeProvider
        attribute="class"
        defaultTheme="system"
        disableTransitionOnChange
        enableSystem
      >
        <header className="flex items-center justify-between w-full p-8">
          <ThemeToggle />
        </header>
        <main className="flex flex-col items-center justify-center w-full flex-1">
          {children}
        </main>
      </ThemeProvider>
    </body>
  </html>
);

export default RootLayout;
